### ISSUE TITLE
bug: unable to select a stop when loading the webpage

### ISSUE THREAD

**Issue by icr4m** [pquline/volr#1]
Some subway lines dont work for "Marseille" the first time they are picked !
![image](https://github.com/user-attachments/assets/310aeac4-058f-4929-a169-9bec1fc9f7b3)

**Comment by pquline** [comment]
@icr4m Thank you for bringing this to my attention. It seems that it might be related to the way the page first loads (ideally it should load a default city). I will look into it as soon as possible and keep you updated.
